name = "SignedCholesky"
uuid = "50dbd362-918f-47d7-a50f-7fe6628962b9"
authors = ["Seth K Asante <seth.kurankyi@gmail.com>"]
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
